### ISSUE TITLE
Custom CORS configuration

### ISSUE THREAD

**Issue by djannot** [solo-io/gloo-portal-issues#106]
**Is your feature request related to a problem? Please describe.**
The VirtualService generated by Gloo Portal includes a CORS configuration but:
- the `content-type` isn't part of the `allowHeaders`
- the `allowOrigin` can't be customized

**Describe the solution you'd like**
We need to either provide a way for the user to provide its own CORS configuration or at least some entries they want to add to the `allowHeaders` and `allowOrigin` arrays.

**Comment by marcogschmidt** [comment]
Adding some context and initial thoughts. We currently set CORS configuration on the Gloo Edge `VirtualService` that is generated for an `Environment` only if any of the API product versions included in that `Environment` are published in one or more `Portal` resources. This is done in order for the "Try it out" feature in the interactive docs for those APIs to work in portal applications (as the requests sent from there are cross-origin). Specifically, we set the following CORS configuration:

```yaml
# The domains of the relevant portals (each with both http and https schemes)
allowOrigin: [] 
# Regular expressions for the domains of the relevant portals 
# that contain DNS wildcards (each with both http and https schemes)
allowOriginRegex: []
allowCredentials: true
allowHeaders:
- api-key
- Authorization
```

Although we allow users to set a wide array of options on the generated `VirtualService`, we currently do not allow setting custom CORS policies in not to conflict with these automatically added ones (see docs [here](https://docs.solo.io/gloo-portal/latest/reference/api/environment/#portal.gloo.solo.io.EnvironmentSpec.GatewayConfig)). I think the best solution would be to relax this constraint and allow users to provide their custom options.
