### ISSUE TITLE
Custom CORS configuration for Gloo Portal + Istio Integration

### ISSUE THREAD

**Issue by ably77** [solo-io/gloo-portal-issues#120]
**Is your feature request related to a problem? Please describe.**

Reference [Custom CORS configuration #106](https://github.com/solo-io/gloo-portal-issues/issues/106)

The issue above addresses custom CORS configuration for Gloo Portal + Gloo Edge, but does not extend to Gloo Portal + Istio. For users testing Gloo Portal + Istio this results in the "Try it Now" feature to fail with `CORS Network Failure`

![image](https://user-images.githubusercontent.com/31321277/135647189-1b0bf63e-e567-479f-b1a9-7892c636b329.png)

Manually modifying the Istio VirtualService and adding `corsPolicy.allowCredentials: true` resolves the CORS issue in the Gloo Portal UI temporarily, but any change in any Portal CR will revert back to the default non-customizable values.

Example valid cors policy that worked for me:
```
- corsPolicy:
      allowHeaders:
      - api-key
      - Authorization
      allowCredentials: true
      allowOrigins:
      - exact: http://petstore.example.com
      - exact: https://petstore.example.com
```

![image](https://user-images.githubusercontent.com/31321277/135647922-d77d3ad3-92be-465c-8a2c-6fe1994f2078.png)

**Describe the solution you'd like**

Would like to see Custom CORS configuration be able to be provided by the user for Gloo Portal + Istio integration, ideally could be provided through the Gateway Options tab feature in the UI. Specifically to add the `allowCredentials: true` to the default, but can also see the customers customizing other entries in the corspolicy potentially as well such as providing additional configuration in `allowHeaders` and `allowOrgins`

**Describe alternatives you've considered**
Cannot move forward at this point because workaround to fix CORS issue manually in Istio VirtualService will be reverted by Portal Controller on any detected change
