### ISSUE TITLE
Docs guide for adding https to API/Environment and Portal UI

### ISSUE THREAD

**Issue by jameshbarton** [solo-io/gloo-portal-issues#136]
**Describe the requested changes**
Adding https support is an important basic use case for many Portal users, both at the API/Environment level and for the Portal UI itself. There is reference documentation that can be pieced together to support this task, but it should be documented in a single user guide.

**Link to any relevant existing docs**
1. Reference [docs](https://docs.solo.io/gloo-portal/latest/reference/api/environment/#portal.gloo.solo.io.EnvironmentSpec.TlsConfig) for the API/Environment that address TLS config.
2. Reference [docs](https://docs.solo.io/gloo-portal/latest/reference/api/portal/#portalspec) for Portal UI that addresses TLS config.
3. Both of the docs above refer to [this Edge SslConfig](https://docs.solo.io/gloo-edge/latest/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/ssl.proto.sk/), but the links are broken from the portal docs (see #127 ):

**Comment by ably77** [comment]
I ran through this exercise yesterday and pieced the bits together, this is what worked for reference:

Set TLS for portal in the `Portal` CR:
```
apiVersion: portal.gloo.solo.io/v1beta1
kind: Portal
metadata:
  name: ecommerce-portal
  namespace: default
spec:
  <omitted>
  tls:
    secretRef:
      name: <secret name>
      namespace: gloo-system
```

Set TLS for APIs in the `Environment` CR:
```
apiVersion: portal.gloo.solo.io/v1beta1
kind: Environment
metadata:
  name: dev
  namespace: default
spec:
  <omitted>
  gatewayConfig:
    disableRoutes: false # we actually want to expose the APIs on a Gateway (optional)
    tls:
      config:
        secretRef:
          name: <secret name>
          namespace: gloo-system
        sniDomains:
        - '<SNI domain>'
      enabled: true
```
