### ISSUE TITLE
same domain name for the Portal and the API gateway

### ISSUE THREAD

**Issue by bcollard** [solo-io/gloo-portal-issues#158]
If I want to manage a single domain name for exposing the developer portal and my APIs
And if I'm able to add a new route for accessing the developer portal web UI, on my existing `VirtualService` (can be pure Gloo Edge or a VS generated by an `Environment`). The route to the dev portal is as simple as:
```yaml
spec:
  virtualHost:
    domains:
    - api.mycompany.com
    routes:
    - matchers:
      - prefix: /
      name: ecommerce-portal.default-route
      routeAction:
        single:
          upstream:
            name: gloo-portal.gloo-portal
            namespace: gloo-portal
```
Then, I would like to disable the generation of the `VirtualService` in the `Portal` CR.
So that, the `Portal` CR is only parsed by the Gloo Portal controller to make decisions about which APIs are visible to who, how users log in, etc.
