### ISSUE TITLE
Abibility to specify cpu/memory request for portal admin dashboard components

### ISSUE THREAD

**Issue by pszeto** [solo-io/gloo-portal-issues#170]
**Is your feature request related to a problem? Please describe.**
Abibility to specify cpu/memory request for portal admin dashboard components

**Describe the solution you'd like**

Similar to how the you're able to define the cpu/memory resources for the portal controller via helm values.
https://docs.solo.io/gloo-portal/latest/reference/helm/
The admin dashboard should have the same ability.

```
# Settings for the Gloo Portal admin dashboard
adminDashboard:
  resources:
    requests:
      cpu: 512m
      memory: 512Mi
```

**Describe alternatives you've considered**

**Additional context**
