### ISSUE TITLE
Support custom AuthConfigs to allow OPA use

### ISSUE THREAD

**Issue by jameshbarton** [solo-io/gloo-portal-issues#172]
**Is your feature request related to a problem? Please describe.**
An enterprise customer wants to use OPA to require presence of a specific header in requests, as in this Gloo Edge [example](https://github.com/solo-io/gloo-edge-use-cases/tree/main/opa-required-header). However, custom AuthConfigs are not supported in Portal, as also described in [this issue](https://github.com/solo-io/dev-portal/issues/1445).

**Describe the solution you'd like**
Allow customer OPA policies to be included via custom AuthConfigs.

**Describe alternatives you've considered**
- Enforce header requirement in OpenAPI spec, perhaps in conjunction with new feature #81 .
- Use a custom WASM filter.
- Use an `invertMatch` with direct response, something like this (not supported in Portal today):
```
kind: VirtualService
metadata:
  name: test-direct-response
  namespace: gloo-system
spec:
  virtualHost:
    routes:
    - matchers:
      - headers: 
        - name: header5
   value: value5
   invertMatch: true
      directResponseAction:
        status: 4xx
        body: "Must contain value5"
```

**Additional context**
Internal discussion: https://solo-io-corp.slack.com/archives/CRV87GM32/p1649356924077649
