### ISSUE TITLE
Virtual Gateway selector not carried forward

### ISSUE THREAD

**Issue by estahn** [solo-io/gloo-portal-issues#22]
Creating an API Product which subsequently creates a virtual gateway is missing the virtual label selector if one is required.

**Comment by marcogschmidt** [comment]
Hi @estahn , I am not sure I understand what you are referring to with "virtual label selector", sorry. Do you mind elaborating on this? It would be useful if you could share your API Product and the Virtual Service you would expect Gloo Portal to generate.

**Comment by estahn** [comment]
We use 2 virtual gateways with the following configuration:

```
  httpGateway:
    virtualServiceSelector:
      environment: qa
```

As far as I understand the `VirtualService` should have a selector, so it can be picked up by the virtual gateway with that particular selector.

**Comment by marcogschmidt** [comment]
Hi @estahn, thanks for the additional info. If I understand your use case correctly, what you want is to configure Gloo Portal to set predictable labels on the `VirtualServices` it generates, so that they can be picked up by your Gateway. Is that correct?

Currently Gloo Portal sets a label on each `VirtualService` it generates based on the name/namespace of the `Environment` that it was generated for. The format of the label is `environments.devportal.solo.io: [ENV_NAME].[ENV_NS]`. For example, if you have this `Environment`:

```yaml
apiVersion: devportal.solo.io/v1alpha1
kind: Environment
metadata:
  name: dev
  namespace: default
spec:
  domains:
  - foo.com
  # [...]
```

Gloo Portal will generate this VS:

```yaml
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  labels:
    # This is the label I am referring to
    environments.devportal.solo.io: dev.default
  name: dev
  namespace: default
spec:
  virtualHost:
    domains:
    - petstore.corp.solo.io
  # [...]
```

So as a temporary workaround you would have to set this on your `Gateway`:

```yaml
httpGateway:
    virtualServiceSelector:
      environments.devportal.solo.io: dev.default
``` 

Or you would need to use one of the other selection criteria (i.e. namespaces or directly referencing the VS by name/ns). I can see how neither of these approaches allow a self-service model though.

We could allow users to configure extra labels on the `Environment` and propagate them to the VS we generate. For example:

```yaml
apiVersion: devportal.solo.io/v1alpha1
kind: Environment
metadata:
  name: dev
  namespace: default
spec:
  routingConfig:
    extraLabels:
      environment: qa
  domains:
  - foo.com
  # [...]
```

Which would generate a VS that matches the selector you provided. Do you think this would work for you?
