### ISSUE TITLE
sniDomain not carried forward

### ISSUE THREAD

**Issue by estahn** [solo-io/gloo-portal-issues#23]
We need to use sniDomains which doesn't seem to be supported.

**Comment by marcogschmidt** [comment]
Hi @estahn , thanks for opening this issue and sorry for the late reply. Could you provide some more information about this issue? Do you want to use SNI when routing to your APIs or for your portal applications?

**Comment by estahn** [comment]
In the `VirtualService` we create we use the following:

```
spec:
  displayName: Production Gateway
  sslConfig:
    secretRef:
      name: wildcard.foobar.com
      namespace: gloo-system
    sniDomains:
    - api.foobar.com
```

There doesn't seem to be an equivalent for the portal. The portal is creating a `VirtualService` without this information.
