### ISSUE TITLE
Portal CRD merge strategy must be improved

### ISSUE THREAD

**Issue by bcollard** [solo-io/gloo-portal-issues#41]
**Describe the bug**
Given a Portal CR, where I've customized the logo + favicon in the admin UI,
When I kubectl apply the Portal CR without these new assets (logo and favicon),
Then, the merged Portal keeps the old reference to `fetchUrl`, but also the new ref to the ConfigMap where my images assets are stored... BUT deletes those ConfigMaps

**To Reproduce**
1. run
```shell
cat <<EOF | kubectl apply -f -
apiVersion: devportal.solo.io/v1alpha1
kind: Portal
metadata:
  name: petstore-portal
  namespace: default
spec:
  displayName: Petstore Portal
  description: The Gloo Portal for the Petstore API
  banner:
    fetchUrl: https://i.imgur.com/EXbBN1a.jpg
  favicon:
    fetchUrl: https://i.imgur.com/QQwlQG3.png
  primaryLogo:
    fetchUrl: https://i.imgur.com/hjgPMNP.png
  customStyling: {}
  staticPages: []

  domains:
  - petstore.example.com

  # This will include all API product of the environment in the portal
  publishedEnvironments:
  - name: dev
    namespace: default
EOF
```
2. upload a new logo, using the admin UI
3. add a new domain in the Portal CR and kubectl apply it
```bash
cat <<EOF | kubectl apply -f -
apiVersion: devportal.solo.io/v1alpha1
kind: Portal
metadata:
  name: petstore-portal
  namespace: default
spec:
  displayName: Petstore Portal
  description: The Gloo Portal for the Petstore API
  banner:
    fetchUrl: https://i.imgur.com/EXbBN1a.jpg
  favicon:
    fetchUrl: https://i.imgur.com/QQwlQG3.png
  primaryLogo:
    fetchUrl: https://i.imgur.com/hjgPMNP.png
  customStyling: {}
  staticPages: []

  domains:
  - petstore.example.com
  - localhost:8080

  # This will include all API product of the environment in the portal
  publishedEnvironments:
  - name: dev
    namespace: default
EOF
```
4. the resulting Portal CR has now 2 different DataSource for the logo. But the ConfigMap is deleted. Portal status is `Failed` :
```yaml
spec:
  allApisPublicViewable: true
  banner:
    fetchUrl: https://i.imgur.com/EXbBN1a.jpg
  customStyling:
    backgroundColor: '#F9F9F9'
    defaultTextColor: '#35393B'
    primaryColor: '#2196C9'
    secondaryColor: '#253E58'
  description: The Gloo Portal for the Petstore API
  displayName: Petstore Portal
  domains:
  - petstore.example.com
  - localhost:8080
  enableIngress: false
  favicon:
    configMap:
      key: favicon
      name: default-petstore-portal-favicon
      namespace: default
    fetchUrl: https://i.imgur.com/QQwlQG3.png
  primaryLogo:
    configMap:
      key: primary-logo
      name: default-petstore-portal-primary-logo
      namespace: default
    fetchUrl: https://i.imgur.com/hjgPMNP.png
  publishedEnvironments:
  - name: dev
    namespace: default
  staticPages: []
status:
  observedGeneration: 3
  publishedEnvironments:
  - apiProducts:
    - name: petstore-product
      namespace: default
    name: dev
    namespace: default
  reason: 'fetching asset favicon: ConfigMap "default-petstore-portal-favicon" not
    found'
  state: Failed
```

**Expected behavior**
Pick only one ref to image datasource

**Additional context**
Add any other context about the problem here, e.g.
- Gloo Portal version 0.6.0
- Kubernetes version 1.20
- Gateway technology and version (e.g. Gloo Edge Enterprise v1.5.11, Istio 1.7): Edge v1.6.20
