### ISSUE TITLE
Select APIDoc operations in APIProducts based on OpenAPI tags

### ISSUE THREAD

**Issue by marcogschmidt** [solo-io/gloo-portal-issues#55]
## Problem summary
When creating an `APIProduct` version that included operations from an OpenAPI `APIDoc`, users currently have two options. Either they enumerate the subset of operations they want to include, e.g.

```yaml
apiVersion: devportal.solo.io/v1alpha1
kind: APIProduct
metadata:
  name: foo
  namespace: default
spec:
  versions:
  - name: v1
    apis:
    - apiDoc:
        name: foo-spec
        namespace: default
      openApi:
        operations:
        - id: operation1
        - id: operation2
``` 

Or they could use a "catch-all" selector (omit the operation list), to include all operations defined in the `APIDoc`:

```yaml
apiVersion: devportal.solo.io/v1alpha1
kind: APIProduct
metadata:
  name: foo
  namespace: default
spec:
  versions:
  - name: v1
    apis:
    - apiDoc:
        name: foo-spec
        namespace: default
``` 

Users have asked to additionally be able to include operations based on OpenAPI [tags](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.0.md#tagObject).
