### ISSUE TITLE
incorrect doc on Environment>gatewayConfig>virtualServiceLabels

### ISSUE THREAD

**Issue by bcollard** [solo-io/gloo-portal-issues#63]
**Describe the requested changes**
The doc is not correct here. It's not an array but a map.

This will not work:
```yaml
  gatewayConfig:
    virtualServiceLabels:
      - key: foo
        value: bar
      - key: abc
        value: def
```

```
E0607 09:07:12.388048       1 reflector.go:127] pkg/mod/k8s.io/client-go@v0.19.7/tools/cache/reflector.go:156: Failed to watch *v1alpha1.Environment: failed to list *v1alpha1.Environment: v1alpha1.EnvironmentList.Items: []v1alpha1.Environment: v1alpha1.Environment.Status: Spec: unmarshalerDecoder: json: cannot unmarshal array into Go value of type map[string]json.RawMessage, error found in #10 byte of ...|:"def"}]}},"status":|..., bigger context ...|foo","value":"bar"},{"key":"abc","value":"def"}]}},"status":{"modifiedDate":"2021-06-07T01:10:14.395|...
```

But this will work:
```yaml
  gatewayConfig:
    virtualServiceLabels:
      foo: bar
      abc: def
```

**Link to any relevant existing docs**
1. https://docs.solo.io/gloo-portal/latest/reference/api/environment/#environmentspec-gatewayconfig

**Additional context**
v1.7.5 (and 1.7.3)
