### ISSUE TITLE
multi-level path rewriting for APIProducts selected by an Environment

### ISSUE THREAD

**Issue by bcollard** [solo-io/gloo-portal-issues#66]
Today, with v0.7.5 and with `edgeIntegration` enabled, we have a way to select different versions of an `APIProduct` depending on the path: `/v1/...` or `/v2/...`, thanks to the new `versionMatching` property.

Some users would like to have more control over the `matchers` generated in a VirtualService.
They asked for:
- a root prefix to be set at the domain level. Ex:`api.example.com/gloo` (business or API governance requirement)
- a way to differentiate `APIProducts` selected by an `Environment`, using predefined prefixes
- having `matchers` working correctly because they are all set to `prefix: /` at the moment

# Current behavior 

Given this `Environment`
```yaml
apiVersion: devportal.solo.io/v1alpha1
kind: Environment
metadata:
  name: shared
  namespace: default
spec:
  domains:
    - shared-api.example.com
  displayInfo:
    description: This environment is meant for developers to deploy and test their APIs.
    displayName: Development
  apiProducts:
    - name: customers-api
      namespace: default
      publishedVersions:
        - name: v1
          externalName: customers
    - name: products-api
      namespace: default
      publishedVersions:
        - name: v1
          externalName: products
        - name: v2
          externalName: products
      versionMatching:
        path: {}
```
Here is the generated `VirtualService`:

```yaml
...
spec:
  displayName: Development
  virtualHost:
    domains:
    - shared-api.example.com
    routes:
    - delegateAction:
        selector:
          labels:
            apiproducts.devportal.solo.io: customers-api.default
            apiproducts.devportal.solo.io/version: v1
            environments.devportal.solo.io: shared.default
      matchers:
      - prefix: /
      name: customers-api.v1
      options: {}
    - delegateAction:
        selector:
          labels:
            apiproducts.devportal.solo.io: products-api.default
            apiproducts.devportal.solo.io/version: v1
            environments.devportal.solo.io: shared.default
      matchers:
      - prefix: /
      name: products-api.v1
      options:
        regexRewrite:
          pattern:
            regex: ^/v1/(.*)$
          substitution: /\1
    - delegateAction:
        selector:
          labels:
            apiproducts.devportal.solo.io: products-api.default
            apiproducts.devportal.solo.io/version: v2
            environments.devportal.solo.io: shared.default
      matchers:
      - prefix: /
      name: products-api.v2
      options:
        regexRewrite:
          pattern:
            regex: ^/v2/(.*)$
          substitution: /\1
```

As you can see, the 3 `matchers` will collide and the 2 versions of the `APIProduct` "products-api" are not differentiated.

# Desired solution

Here is a proposal for "multi-level" prefix management:

```yaml
spec:
  domains:
    - name: api.example.com # NEW!
      rootPrefix: gloo # NEW!
  apiProducts:
    - name: customers
      namespace: default
      publishedVersions:
        - name: v1
          externalName: customers
        - name: v2
          externalName: customers
      versionMatching:
        path: {}
      basePath: customers # NEW!
    - name: products
      namespace: default
      publishedVersions:
        - name: v1
          externalName: products
      basePath: products # NEW!
```      

The generated `VirtualService` would be:

```yaml
spec:
  virtualHost:
    domains:
    - api.example.com
    routes:
      - delegateAction:
          selector:
            labels:
              apiproducts.devportal.solo.io: customers-api.default
              apiproducts.devportal.solo.io/version: v1
              environments.devportal.solo.io: shared.default
        matchers:
        - prefix: /gloo/customers/v1 # NEW!
        name: customers-api.v1
        options:
          regexRewrite:
            pattern:
              regex: ^/gloo/customers/v1/(.*)$ # NEW!
            substitution: /\1
      - delegateAction:
          selector:
            labels:
              apiproducts.devportal.solo.io: customers-api.default
              apiproducts.devportal.solo.io/version: v2
              environments.devportal.solo.io: shared.default
        matchers:
        - prefix: /gloo/customers/v2 # NEW!
        name: customers-api.v2
        options:
          regexRewrite:
            pattern:
              regex: ^/gloo/customers/v2/(.*)$ # NEW!
            substitution: /\1
      - delegateAction:
          selector:
            labels:
              apiproducts.devportal.solo.io: products-api.default
              apiproducts.devportal.solo.io/version: v1
              environments.devportal.solo.io: shared.default
        matchers:
          - prefix: /gloo/products # NEW!
        name: products-api.v1
        options:
          regexRewrite:
            pattern:
              regex: ^/gloo/products/(.*)$ # NEW!
            substitution: /\1
```

Matchers and regex patterns are build like this: `<rootPrefix> + <basePath> + <version name>` --> of course, only if these properties are set in the Environment 

**Additional context**
Gloo Portal v0.7.5, with `edgeIntegration: true`
Gloo Edge v1.8.0 beta 6

**Comment by marcogschmidt** [comment]
This change has been implemented and will be included in Gloo Portal v1.0.0, which will be released this week. Here is an example of the new API for base path rewrites:

```yaml
apiVersion: portal.gloo.solo.io/v1beta1
kind: Environment
metadata:
  name: test-environment
  namespace: dev-portal
spec:
  domains:
  - petstore.example.com
  basePath: api
  apiProducts:
  - basePath: '{%version%}' # <--- this is a reserved value that Gloo Portal will replace with the ID of the relevant API product version
    labels:
    - key: app
      operator: Equals
      values:
      - petstore
    namespaces:
    - '*'
```

**Comment by bcollard** [comment]
There is a glitch with `basePath: "{%version%}"`
The regex in the generated VS looks like that:
```yaml
regexRewrite:
          pattern:
            regex: ^/ecommerce/"v1"/(.*)$
          substitution: /\1
```
☝️ see the double quotes surrounding the version name
Should I open a new issue? 
@chrisgaun it's for the customers we spoke about last Friday
