### ISSUE TITLE
plan display name cannot be empty

### ISSUE THREAD

**Issue by bcollard** [solo-io/gloo-portal-issues#70]
**Describe the bug**
I created a new usage plan in the admin UI for a given APIProduct in my environment.
I left the `displayName` field empty

dev-portal is complaining about this:
```yaml
status:
  modifiedDate: "2021-06-15T12:36:21.960856400Z"
  observedGeneration: 6
  reason: "invalid usage plans for API Product default:customers-api: 1 error occurred:\n\t*
    plan display name cannot be empty\n\n"
  state: Processing
```

**Expected behavior**
Deny empty field in the admin web UI

**Additional context**
Add any other context about the problem here, e.g.
- Gloo Portal version v0.7.5

**Comment by bcollard** [comment]
When I re-open it, there is a default value set:
![image](https://user-images.githubusercontent.com/9626829/122054201-c0293e80-cde7-11eb-8e9c-89f4bd50243c.png)


but the Environment CR is not updated:
```yaml
spec:
  apiProducts:
  - name: customers-api
    namespace: default
    plans:
    - authPolicy:
        apiKey: {}
      displayName: use api keys
      name: keys
    - authPolicy:
        apiKey: {}
      name: key-bis
      rateLimit:
        requestsPerUnit: 9999999
        unit: MINUTE
```
