### ISSUE TITLE
being able to narrow down the list of HTTP verbs available to a Client, for a given APIProduct operation

### ISSUE THREAD

**Issue by bcollard** [solo-io/gloo-portal-issues#71]
**Is your feature request related to a problem? Please describe.**
A customer asked for a way to narrow down the list of HTTP verbs that is available to a Client, for a given APIProduct operation.

It could be a new property in the usage plan of an Environment, like:
```yaml
      plans:
        - name: keys
          displayName: use api keys
          authPolicy:
            apiKey: {}
          subset: # NEW!
            - operation: findPetById
              verbs:
                - GET
                - OPTIONS
```

It's just a suggestion! feel free to place this kind of config in a more relevant CRD / place.

**Additional context**
Gloo Portal v0.7.5
