### ISSUE TITLE
Some Portal creation failures incorrectly result in `Succeeded` state

### ISSUE THREAD

**Issue by jameshbarton** [solo-io/gloo-portal-issues#91]
**Describe the bug**
Sometimes when Portal creation fails like in #90 , the Portal CR incorrectly reports its state as `Succeeded`.

**To Reproduce**
1. See #90 
2. Observe incorrect `Succeeded` state in Portal CR:
```
  status:
    observedGeneration: 1
    publishedEnvironments:
    - apiProducts:
      - name: petstore-product
        namespace: default
      name: dev
      namespace: default
    state: Succeeded
```

**Expected behavior**
A failed Portal creation should have a matching failed status.

**Additional context**
- Gloo Portal 0.7.5
- OCP 4.7.9
- GlooEE 1.7.7
