### ISSUE TITLE
version [...] does not exist on API Product [...]

### ISSUE THREAD

**Issue by bcollard** [solo-io/gloo-portal-issues#96]
**Describe the bug**
Given an existing Environment referencing apiproducts as in:
```yaml
  apiProducts:
    - namespaces:
      - "*" 
      labels:
      - key: app
        operator: In
        values:
        - petstore
      versions:
        names:
        - v1
        - v2
```

If I remove the v2 from the targeted APIProduct, then the controller reports this error:
```yaml
status:
  modifiedDate: "2021-08-16T12:58:28.979262736Z"
  observedGeneration: 1
  reason: version [v1] does not exist on API Product [petstore-product.default]
  state: Invalid
```

**Expected behavior**
- the VirtualService should be updated even if one (or more) version(s) is not found. Reporting an error could be an option if no version is found at all
- the missing version reported in the error message is misleading. In my case, it says v1 is missing whereas v2 is actually missing.

**Additional context**
Add any other context about the problem here, e.g.
- Gloo Portal version 1.1.0-beta4
- Gateway technology: Gloo Edge EE 1.8.5
