### ISSUE TITLE
Allow setting routing config at API doc level in API product

### ISSUE THREAD

**Issue by marcogschmidt** [solo-io/gloo-portal-issues#99]
## Problem
Currently users can set routing configuration at two levels on an API product version:
- at the root (what we sometimes call a _default route_): in this case the routing config applies to all operations by default;
- on each operation: in this case it overwrites the root config for a given operation

Here is an example that illustrates this:

```yaml
apiVersion: portal.gloo.solo.io/v1beta1
kind: APIProduct
metadata:
  name: foo
  namespace: gloo-portal
spec:
  versions:
  - name: v1
    apis:
    - apiDoc:
        name: petstore-api-spec
        namespace: gloo-portal
      openApi:
        operations:
        - id: findPets
        - id: findPetById
          gatewayConfig:
            # Use this route just for this operation
            route: { }
    gatewayConfig:
      # This is the "default" route that applies to all operations
      # if no route is set on an operation.
      route: {}
```

A common use case involves an API product that consists of multiple API docs, each of which is backed by a different service. It is possible to configure this scenario, but the configuration would be quite verbose as users need to specify the route configuration on each operation:

```yaml

apiVersion: portal.gloo.solo.io/v1beta1
kind: APIProduct
metadata:
  name: my-product
  namespace: default
spec:
  versions:
  - name: v1
    apis:
    - apiDoc:
        name: foo
        namespace: default
      openApi:
        operations:
        - id: getFoo
          gatewayConfig:
            route:
              routeRef:
                name: foo-v1
                namespace: default
        - id: createFoo
          gatewayConfig:
            route:
              routeRef:
                name: foo-v1
                namespace: default
        # [...]
    - apiDoc:
        name: bar
        namespace: default
      openApi:
        operations:
        - id: getBar
          gatewayConfig:
            route:
              routeRef:
                name: bar-v1
                namespace: default
        - id: createBar
          gatewayConfig:
            route:
              routeRef:
                name: bar-v1
                namespace: default
        # [...]
```

## Proposed solution
To allow for more concise configuration, we could allow users to set routing configuration at the API doc selector level. That configuration would overwrite the default root config and apply to all the operations that belong to that API doc, unless overwritten by operation-specific config.

With this model the previous example would become:

```yaml
apiVersion: portal.gloo.solo.io/v1beta1
kind: APIProduct
metadata:
  name: sports-data
  namespace: default
spec:
  versions:
  - name: v1
    # This is the config that applies to
    # the whole product version by default
    gatewayConfig:
      route: {}
    apis:
    - apiDoc:
        name: foo
        namespace: default
      # This is the config that applies to
      # all the operations imported from this
      # API doc by default.
      # This overwrites the root config.
      gatewayConfig:
        route:
          routeRef:
            name: foo-v1
            namespace: default
      openApi:
        operations:
        - id: getFoo
        - id: createFoo
        - id: fancyFoo
          # Route config for this specific route.
          # This overwrites the config at the root
          # and API doc levels.
          gatewayConfig:
            route: {}
        # [...]
    - apiDoc:
        name: football
        namespace: default
      gatewayConfig:
        route:
          routeRef:
            name: bar-v1
            namespace: default
      openApi:
        operations:
        - id: getBar
        - id: createBar
        # [...]
```
